### ISSUE TITLE
cognexa/archlinux is broken

### ISSUE THREAD

**Issue by blazekadam** [Cognexa/dockerfiles#13]
```
➜ red@eric ~/cati  git:(visualize-timelapse) docker run -it --rm cognexa/archlinux sh
Unable to find image 'cognexa/archlinux:latest' locally
latest: Pulling from cognexa/archlinux
50dcfd569c3f: Already exists
2d3381b27f03: Already exists
5108e623402f: Already exists
9da0f53eea19: Already exists
dc5963443046: Pull complete
7a71e17125a8: Pull complete
2b0736c43ce8: Pull complete
35782c0f9d93: Pull complete
Digest: sha256:4dc16315091bdb707df9372cf6c5e0510c5608cd48f2f7046206469067dec8a9
Status: Downloaded newer image for cognexa/archlinux:latest
sh-4.4# python
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libhdf5.so.101: cannot open shared object file: No such file or directory
>>> 
```

**Comment by blazekadam** [comment]
After `pacman -S hdf5` you ll get
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by blazekadam** [comment]
Can be fixed with

`pacman -S gtkglext hdf5`

which is strange since `opencv` has those packages in dependencies...

**Comment by FloopCZ** [comment]
Hi, yes. I have also encountered this one, but I tend to forget about this dependency all the time.

It is in dependencies, however, only in optional dependencies. And unfortunately, opencv python module requires even these two (as far as I remember, gtkglext was not needed, only hdf5).
